### ISSUE TITLE
Compiler warning --> implicit conversion from float to int

### ISSUE THREAD

**Issue by hjmjohnson** [NIFTI-Imaging/nifti_clib#1]
Rick,

This is concerning to me:  

```
/Users/johnsonhj/src/nifti_clib/nifticdf/nifticdf.c:10867:41: warning: using integer absolute value function 'abs' when argument is of floating
      point type [-Wabsolute-value]
                            pq.q = exp(-abs(val))    ; pq.p = 1.0-pq.q; break;
                                        ^
/Users/johnsonhj/src/nifti_clib/nifticdf/nifticdf.c:10867:41: note: use function 'fabs' instead
                            pq.q = exp(-abs(val))    ; pq.p = 1.0-pq.q; break;
                                        ^~~
                                        fabs
/Users/johnsonhj/src/nifti_clib/nifticdf/nifticdf.c:10869:45: warning: using integer absolute value function 'abs' when argument is of floating
      point type [-Wabsolute-value]
                            pq.q = pow(10.,-abs(val)); pq.p = 1.0-pq.q; break;
                                            ^
/Users/johnsonhj/src/nifti_clib/nifticdf/nifticdf.c:10869:45: note: use function 'fabs' instead
                            pq.q = pow(10.,-abs(val)); pq.p = 1.0-pq.q; break;
                                            ^~~
                                            fabs
```
It seems that we should either static cast to int, or use fabs.

I'd appreciate your comments.

**Comment by hjmjohnson** [comment]
@afni-rickr You should definitely do this as a PR, but since you have write access (as an administrator) on this nifti_clib repo you could bypass making a fork.

1) Check-out this repo
2) make a branch
3) modify branch
4) push branch
5) goto this website and make PR from the branch
... review... approve.... rebasemerge
6) house clean and remove the merged branch sometime later.

**Comment by afni-rickr** [comment]
Oh great, that is indeed what I did (after looking to mimic yours).  So will we have to select 'rebasemerge' whenever we approve the PRs?  I guess I should just try it, but I left you as a reviewer, just to try that out, too.  :)

**Comment by hjmjohnson** [comment]
The recent patches are now resulting in a perfectly green dashboard.  👍 


![image](https://user-images.githubusercontent.com/313970/49666378-88bec780-fa1d-11e8-8340-ce59fb927836.png)

**Comment by afni-rickr** [comment]
Beautiful...
