### ISSUE TITLE
What is nifti-2?  What is its state?

### ISSUE THREAD

**Issue by hjmjohnson** [NIFTI-Imaging/nifti_clib#10]
https://nifti.nimh.nih.gov/nifti-2

NIfTI-2 header file - C header file that defines the NIfTI-2 format (not final)

**Comment by hjmjohnson** [comment]
@afni-rickr should cifti and nifti-2 have some documentation added about the intended use?

**Comment by hjmjohnson** [comment]
Rick,

This is also related to #12 .  Could you provide a bit of feedback on the desired inclusion of the cifti and nifti2 with respect to their maturity and the desire to include them as CMake build options.

Thanks,
Hans

**Comment by afni-rickr** [comment]
We have not written almost any translation code in AFNI to be able to read and write CIFTI datasets (translating to/from AFNI format).  Consequently, the cifti code does not really see use, and so it cannot be called mature.

The gifti library has been used quite a bit, though we have still not switched to GIFTI as our "native" surface file format (that is still NIML, an AFNI-specific format).  Maybe I should set afni_proc.py up to do that, as well as 3dVol2Surf.  But that library is pretty mature.
