### ISSUE TITLE
nifti_read_header fails for .gz files.

### ISSUE THREAD

**Issue by acdemiralp** [NIFTI-Imaging/nifti_clib#100]
This is due to the fact that following 4 is hardcoded in `nifti_find_file_extension` which gets called by `nifti_read_header`:
```
   if ( ! name ) return NULL;

   len = (int)strlen(name);
   if ( len < 4 ) return NULL;

   ext = name + len - 4;
```
but .gz is a 3 character extension unlike the others leading to ext being "i.gz" and hence the extension not being detected.

**Comment by afni-rickr** [comment]
That section of code is assuming there is no .gz extension.  The HAVE_ZLIB code just a few lines farther is where a .gz extension is considered.
Note that i.gz is not a valid NIFTI filename.  It should be i.nii.gz.

**Comment by acdemiralp** [comment]
Ah I see. I switched to VTK's third-party standalone NIFTI reader simply because this library took a precious week off my life. During this time, I considered to do a re-write and a full C++ wrapper for you, but quite frankly I do not have time for this.
