### ISSUE TITLE
changelog since last official release?

### ISSUE THREAD

**Issue by gdevenyi** [NIFTI-Imaging/nifti_clib#118]
With this big version bump, it would be helpful to have a changelog describing the changes, especially if they're API changes.

**Comment by leej3** [comment]
There is a [list of updates](https://github.com/NIFTI-Imaging/nifti_clib/blob/ff1371b24a859dbf8a3eaaed5b82dc4bc096a9b9/Updates.txt#L108). Are you suggesting we add more, or make them more visible?

Regarding changes API/ABI, only znzlib  has breaking changes as far as I understand. We are not certain people use this  directly.  The nifti library's expose the same interfaces but now handle larger files under the hood.

**Comment by gdevenyi** [comment]
Thanks! More visible on the GitHub release page please.

**Comment by leej3** [comment]
Fixed. Thanks for pointing that out!

**Comment by gdevenyi** [comment]
Thanks!
