### ISSUE TITLE
shared variants available? or static only? 'utils' directory missing.

### ISSUE THREAD

**Issue by i3roly** [NIFTI-Imaging/nifti_clib#121]
hi,

so i checked out the version tagged '3.0.0' and the 'utils' directory is missing.

it isn't critical, but it does stop the make command from exiting cleanly.

for example, the command "make all" invokes building all subdirectories, one being 'utils' which does not exist in the tree.

of course, removing the rule fixes the issue. just wanted to let you know.

i am very, *very* **very** excited to see this project getting life again. 

it has been eight years, but it feels like yesterday :)

**Comment by leej3** [comment]
Thanks for the the encouraging words and pointing out the error. That has been fixed in the recent release. It's worth noting that we are primarily using the cmake build system now.

For shared libs from the project repository:

```
mkdir build
cd build
cmake -DBUILD_SHARED_LIBS=ON ..
```
