### ISSUE TITLE
Receiving "short header read" error. Unsure what is causing it.

### ISSUE THREAD

**Issue by id-b3** [NIFTI-Imaging/nifti_clib#132]
https://github.com/NIFTI-Imaging/nifti_clib/blob/7934f742f435c3d6628a1099cd2dba14d6cd2216/niftilib/nifti1_io.c#L4212

I'm receiving the short header read error, and I've traced it back to this line. However, my nifti files do contain headers. I'm not sure what the issue is or how to resolve it, what should this error prompt me to do?

**Comment by gdevenyi** [comment]
What generated your NIFTI files?

What happens if you use something we know works properly to examine the header (ANTs PrintHeader or fslinfo)?

**Comment by id-b3** [comment]
The NIFTI files were generated by dcm2niix then fed through a segmentation tool. The result from fslinfo is:

> data_type      UINT8
> dim1           512
> dim2           512
> dim3           566
> dim4           1
> datatype       2
> pixdim1        0.683594
> pixdim2        0.683594
> pixdim3        0.700012
> pixdim4        1.000000
> cal_max        0.0000
> cal_min        0.0000
> file_type      NIFTI-1+

**Comment by gdevenyi** [comment]
> then fed through a segmentation tool. 

This sounds to me like the origin of the issues. You should probably share the code and details of the nifti interface implementaiton.

**Comment by id-b3** [comment]
The segmentation algorithm read/write functions for nifti seems to use nibabel #[https://github.com/antonioguj/bronchinet/blob/8788be6caef3d10228feab780379ff1af75e583d/src/dataloaders/imagefilereader.py#L96-L101](as seen here.)

I found this in the nifti documentation [https://nifti.nimh.nih.gov/nifti-1/data/minimal.txt](the minimum header file.) Does this mean that the "short header read" error message is flagging the file as missing some of these compulsory header entries?

**Comment by gdevenyi** [comment]
Looks like you should be opening a bug against nibabel since its creating the file.

**Comment by id-b3** [comment]
Possibly, however the only thing that I've changed in the environment is to update the niftyclibs. I'll revert back to an earlier version and see if the error persists.

**Comment by afni-rickr** [comment]
Hi @id-b3, that "short header read" message suggests the file isn't even big enough to contain the header, much less any data.

0. Is nifti_tool available to you?
    `which nifti_tool`
1. What is the size of the file?   
    `ls -l FILENAME`
    `wc -c FILENAME`
2. Is it compressed, yet being read with a library that does not have compression?
   `file FILENAME`
   `nifti_tool -with_zlib`
3. What does nifti_tool say about the file, especially if you try to read/write with it?
    `nifti_tool -infile FILENAME -cbl -prefix NEW.nii`
or verbosely:
    `nifti_tool -infile FILENAME -cbl -prefix NEW.nii -debug 5`

**Comment by id-b3** [comment]
Hi @afni-rickr,

I see the issue now, the code is using the CImg library alongside the Nifti c lib for manipulating nifti files. Somewhere in that process, the resulting file has a size of 0 bytes. So that is why I'm having the error. I'll have to see what is hapenning between CImg and nifti to figure it out. Thank you for your help!
