### ISSUE TITLE
Link Time Optimization (LTO) fails due to duplicate symbols

### ISSUE THREAD

**Issue by hjmjohnson** [NIFTI-Imaging/nifti_clib#37]
@afni-rickr I'd love your advice/help in identifying a way to resolve this linkage problem.

#31 builds identify problems that will prevent LTO (inter procedure optimization).

When building nifti2, these symbols violate the "One Definition Rule (ODR)"

ld: 98 duplicate symbols for architecture x86_64
duplicate symbol _nifti_disp_matrix_orient in:
    libnifti2.a(nifti2_io.c.o)  ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_image_load_bricks in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_image_free in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_update_dims_from_array in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _valid_nifti_brick_list in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_intent_string in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_slice_string in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_datatype_sizes in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_quatern_to_mat44 in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_mat44_to_orientation in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_orientation_string in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_datatype_string in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_is_inttype in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_units_string in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_xform_string in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_swap_16bytes in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_swap_Nbytes in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _swap_nifti_header in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_swap_as_analyze in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _old_swap_nifti_header in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_get_filesize in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_get_volsize in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_fileexists in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_mat44_to_quatern in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_mat33_polar in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_mat44_inverse in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_make_orthog_mat44 in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_mat33_inverse in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_mat33_determ in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_mat33_rownorm in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_mat33_colnorm in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_mat33_mul in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_swap_2bytes in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_swap_4bytes in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_swap_8bytes in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_is_complete_filename in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_find_file_extension in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_validfilename in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_is_gzfile in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_compiled_with_zlib in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_makebasename in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_set_debug_level in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_set_skip_blank_ext in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_set_allow_upper_fext in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_findhdrname in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_findimgname in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_makehdrname in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_makeimgname in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_set_filenames in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_short_order in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_set_type_from_names in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_type_and_names_match in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _is_valid_nifti_type in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_is_valid_datatype in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _disp_nifti_1_header in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_image_open in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_read_header in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_datatype_is_valid in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_read_ascii_image in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_image_infodump in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_image_load in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_image_from_ascii in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_add_extension in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _valid_nifti_extensions in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_is_valid_ecode in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_read_buffer in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_image_unload in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_free_extensions in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_image_to_ascii in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_write_buffer in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_write_all_data in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_simple_init_nim in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_make_new_nim in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_copy_extensions in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_extension_size in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_set_iname_offset in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_image_write_hdr_img in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_image_write_hdr_img2 in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_write_ascii_image in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_image_write in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_image_write_bricks in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_copy_nim_info in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_nim_is_valid in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_nim_has_valid_dims in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_read_collapsed_image in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_read_subregion_image in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_get_intlist in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_datatype_from_string in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_datatype_to_string in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_test_datatype_sizes in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_disp_type_list in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_free_NBL in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_disp_lib_version in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_image_read in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_image_read_bricks in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _is_nifti_file in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_strdup in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)
duplicate symbol _nifti_disp_lib_hist in:
    libnifti2.a(nifti2_io.c.o)    ../niftilib/libniftiio.a(nifti1_io.c.o)

**Comment by afni-rickr** [comment]
Hi @hjmjohnson.  The nifti2 library replaces the nifti1 library, rather than depending on it.  So yes, most of the functions should have the same name.  From nifti1, only nifti1.h is used for nifti2.  I am not sure how that should be configured in cmake.

**Comment by hjmjohnson** [comment]
The problem is at link time.

nifti1.h defines @ line 453:
void         nifti_disp_lib_hist( void ) ;     /* to display library history */

nifti2.h defines @line 447:
void         nifti_disp_lib_hist( int ver ) ;  /* to display library history */

====
in nifti2_io.h lines 20 and 21:
#include "nifti1.h"                  /*** NIFTI-1 header specification ***/
#include "nifti2.h"                  /*** NIFTI-2 header specification ***/

=====
So both function prototypes are defined and I assumed that the linkage needed to occur.

**Comment by hjmjohnson** [comment]
OHHH!  I see now!!    I was confusing nifti1_io.h and nifti1.h.

--- I think the best solution (from a package manager perspective) is to duplicate that file in the nifti2 directory.  If the intent is for nifti2 to be stand-alone and independent, then it should NOT depend on some small part of nifti1.

**Comment by afni-rickr** [comment]
Sure.  I wasn't quite sure what to do with nifti1.h.  That essentially defines the NIFTI-1 standard, with associated macros, so it seemed strange to dupe it.  But it is okay, that would just mean changes would have to be tracked between them.  If it is duplicated, maybe a test should be added to compare the files.

**Comment by hjmjohnson** [comment]
Thanks.  Will do. That actually helps me out a lot!  I thought that nifti2 linked against nifti1.  

For ITK, i think that perhaps nifti2 will be a drop in replacement for nifti1 with minimal changes.

**Comment by hjmjohnson** [comment]
Documentation for pre changes: 

```
# https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/Graphviz
 cmake --graphviz=test.dot .
 dot -Tpdf -O test.dot
```
![image](https://user-images.githubusercontent.com/313970/50186706-4761ce00-02e1-11e9-9305-daf45461c89a.png)


POST changes:
![screen shot 2018-12-18 at 4 43 39 pm](https://user-images.githubusercontent.com/313970/50187582-1cc54480-02e4-11e9-8257-f41fbd6f359d.png)
