### ISSUE TITLE
Your NITRC tool/resource, NIfTI, has the following broken links:

### ISSUE THREAD

**Issue by hjmjohnson** [NIFTI-Imaging/nifti_clib#60]
Module: Custom Tool Menu Entries
Name: SCM
URL: http://sourceforge.net/cvs/?group_id=126549
Tested on 2019-01-05 at 13:03:04 and again on 2019-01-11 at 04:31:33.

Our automated link-checker was unable to validate the above links.  If the links appear to be correct and display properly in your web browser, it is possible that your server is rejecting our automated download attempt.

Please visit the Admin Setup Wizard ( http://www.nitrc.org/wizard/index.php?group_id=26 ) to fully update your tool/resource in just a few minutes.

Alternately, go to the tool/resource Admin Page ( http://www.nitrc.org/project/admin/?group_id=26 ) to update the links and remove any features you do not want to use at this time.

Once you've removed the bad links, you won't receive this pesky error message anymore, and NITRC will be boosted in Google's search, potentially bringing even more new users to your tool/resource (bad links negatively impact Google's search algorithm).

**Comment by afni-rickr** [comment]
@hjmjohnson I think they are fixed now, or at least the 2 that I saw.  Brian did it (I am not actually an admin).

**Comment by hjmjohnson** [comment]
Thanks
