### ISSUE TITLE
Why does this format still exist?

### ISSUE THREAD

**Issue by acdemiralp** [NIFTI-Imaging/nifti_clib#64]
Partially rhetoric, partially actual question. Why do you maintain this when HDF5, a more general, faster, well-documented, proper file format exists for storing exactly the same type of data, but for more disciplines. Additionally, why 3 libraries consisting of single files rather than 1 library? The code is extremely out of date (C 1989 I think?), and is full of horrendous practices such as redefining CR and LF which breaks on certain operating systems. Modernizing it would take several months effort with a full team, which would likely be slower than developing a new library, and this is the exact the definition of unmaintainable. I mourn for your developers.

**Comment by leej3** [comment]
Hi Ali,

Out of interest, was it specifically building on windows that was the problem or did you have other issues for osx/linux? Thanks.

**Comment by acdemiralp** [comment]
Dear John,

I have gotten to build it on all systems by creating a new cmake project using the sources only. I am attaching the CMake below. There is one catch, I'm building nifti-1 and znzlib into a single library. I initially had nifti-2 also, but there was function name conflicts so I took it out.
[nifti-single.zip](https://github.com/NIFTI-Imaging/nifti_clib/files/3010465/nifti-single.zip)

**Comment by leej3** [comment]
Thanks for that. That is certainly a simpler build pattern. Some nice tricks I shall be using myself. 

Regarding merging libraries, I suspect that would not be possible. Pre-existing c implementations of nifti/gifti exist in the widely used ITK, FSL, AFNI, and dcm2niix, among others. This repo is an attempt to consolidate some of those efforts into one place to prevent divergence. With that, backwards compatibility becomes a  priority. I'll try to get more feedback on what could happen. A diff of the sources you provide have reversed some of the recent changes to the c code. Not sure whether that was deliberate?

Also, for debugging this for Windows... was your intent to build for native windows or Cygwin or something like that? Were you using Visual Studio and its compilers? With that said, a lot of scientific computing happens on Linux clusters, that might be part of the reason why it is not supported as well as it could be.

For what its worth, my opinion on why the format still exists: standardization within the field and interoperability between softwares is more valuable, and more of a challenge. They outweigh any benefits from a more modern format and the struggles involved in its adoption. I have no doubt that others, especially those who went through the harrowing experience of reaching the compromise that is the NIFTI standard (a viable replacement for the many pre-existing and competing file-formats), would have a deeper and more nuanced opinion that would likely take quite some time to articulate!

Also, depending on the purpose/extent of your exploration of these tools etc. it might be worth your time to check out nibabel (for IO using python), nilearn, nipype, brainiak, NIDM, and BIDS (and the associated BIDS-apps).

**Comment by hjmjohnson** [comment]
@leej3  Nicely put response.  Summary "support of historical code bases spanning many decades and 1000's of developers supported many of the design decisions in the NIFTI standard".  Backward compatibility is incredibly valuable.

**Comment by gdevenyi** [comment]
MINC wrote it's standard, then wrote the code, so you may also want to investigate that for a standardized approach to multidimensional imaging data
