### ISSUE TITLE
Reserve or codify FSL intent codes

### ISSUE THREAD

**Issue by effigies** [NIFTI-Imaging/nifti_clib#66]
Just want to flag that FSL has custom intent codes for [FNIRT](https://github.com/mshvartsman/FSL/blob/7aa2932949129f5c61af912ea677d4dbda843895/src/warpfns/fnirt_file_reader.h#L100-L107) and [TOPUP](https://github.com/mshvartsman/FSL/blob/fsl-5.0.9/src/topup/topup_file_io.h#L100-L106) files.

Because these exist in the wild, we accept them in nibabel (nipy/nibabel#528; [nibabel/nifti1.py#L239-L251](https://github.com/nipy/nibabel/blob/ed3cdb5a33fdf1dd49e037600927f3b213f61f08/nibabel/nifti1.py#L239-L251)).

I don't have a strong opinion on whether these should be adopted in the official standard, but they should probably be reserved with a note, so a clash doesn't occur in the future.

cc @pauldmccarthy

**Comment by hjmjohnson** [comment]
@effigies Could you please make a pull request so that it can be be reviewed and potentially included upstream?  My feeling is that adding intent codes can be done.
